delphix/recovery-environment

base_img/init_functions
If you exit the shell from the console of the recovery environment, or don't log in promptly, the login command will exit and this will cause the init process to exit, which panics the system. We need to prevent that, by looping over the login command.
=> Relaunch shell after it exits

debian/postinst, scripts/stage1.sh
This PR adds the ZFS utilities to the recovery environment, so we can import and modify pools as needed in order to prevent further failed boots. This PR is intended to merged in conjunction with https://github.com/delphix/linux-pkg/pull/102. It was tested with ab-pre-push, and by loading the built recovery environment onto a test VM to verify functionality.
=> Add zfs utilities

Makefile, debian/postinst
The debsums -c check we do as part of the appliance build process fails when the recovery.img file is modified as part of the postinst and recovery_sync steps. We should install the base recovery.img file to a different location and create a new copy in postinst that will actually be used to boot the system.
=> Install base image to separate location to satisfy debsums

Makefile
This PR updates the uninstall entry for the recovery image, which was neglected in the previous PR.
=> Update incorrect uninstall entry

scripts/delphix-bootcount.service, scripts/recovery_sync
This fixes an issue where the recovery environment can become corrupted if the system goes down while we're syncing the recovery environment.
=> Write to temporary file, mv atomically to target

Makefile, scripts/bootcount_reset, scripts/delphix-bootcount.service
Because the recovery-environment package is installed in a chroot, the install steps that set up the recovery environment don't actually affect the rpool of the Delphix Engine. As a result, we need to handle that step later. The simplest solution is to have the automated bootcount reset procedure create a bootenv if it doesn't detect a valid one. This has the added advantage that if the bootenv is corrupted by some means, it will be recreated after the next successful boot.
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3890/ (in progress)
a VM from this run was cloned and the fix was verified manually.
=> DLPX-71297 delphix-bootcount service fails to start on master

Makefile, scripts/bootcount_reset, scripts/delphix-bootcount.service
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3892/ (in progress)
Clean cherry-pick from master
=> DLPX-71356 [Backport of DLPX-71297 to 6.0.4.0] delphix-bootcount service fails to start on master

debian/postinst, scripts/42_recovery, scripts/bootcount_reset
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3950/console
Manual testing performed with an ab-pre-push VM; machine was rebooted repeatedly until it entered the recovery environment, at which time ssh and http connectivity was verified. The package was then reinstalled, to emulate the upgrade workflow, and the test was repeated. All tests were successful.
=> DLPX-71708 Recovery environment fails to boot

debian/postinst, scripts/42_recovery, scripts/bootcount_reset
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3951/console
Manual testing performed with an ab-pre-push VM; machine was rebooted repeatedly until it entered the recovery environment, at which time ssh and http connectivity was verified. The package was then reinstalled, to emulate the upgrade workflow, and the test was repeated. All tests were successful.
=> DLPX-71720 [Backport of DLPX-71708 to 6.0.4.0] Recovery environment fails to boot

scripts/recovery_sync
Testing: 
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3983/console (in progress)
Cloned ab-pre-push VM, verified that recovery environment was network reachable.
Evaluation:
By default, systemd uses the old style name scheme for network devices; this causes the first network interface on the Delphix Engine to be registered as eth0. A configuration file (/lib/systemd/network/99-default.link) causes systemd to use the kernel's provided name (ens160, on vmware) instead. This configuration file needs to be synced into the recovery environment as well, in order for the recovery environment to properly configure the system's network devices automatically.
This regression was triggered when a recent change was pushed that changed …
=> DLPX-71777 Recovery environment is unreachable from network

scripts/recovery_sync
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4042/
Tested manually by running recovery_sync with the nginx directory not present.
=> DLPX-71888 delphix-bootcount service fails due to missing nginx config files

debian/postinst
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4119/console Failure appears environmental
Upgrade tests from 6.0.3.0 in progress http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/upgrade-testing/4031/console
=> DLPX-72161 [Backport of DLPX-72155 to 6.0.4.2] Cancelled upgrades can render engine unbootable

base_img/hooks/networkd, scripts/recovery_sync, scripts/stage1.sh
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4238/
Manually tested by adding a search domain to the DNS config, and then rebooting into the recovery environment that it was present there as well.
=> DLPX-71822 recovery environment should have DNS configuration

scripts/recovery_sync
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4256/
=> DLPX-72418 [Backport of DLPX-72389 to 6.0.6.0] delphix-bootcount service fails due to missing image

scripts/recovery_sync
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4237/
=> DLPX-72485 [Backport of DLPX-71888 to 6.0.6.0] delphix-bootcount service fails due to missing nginx config files

base_img/hooks/networkd, scripts/recovery_sync, scripts/stage1.sh
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4370/ test failure appears environmental
=> DLPX-72848 [Backport of DLPX-71822 to 6.0.6.0] recovery environment should have DNS configuration

debian/postinst
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4825/console
=> DLPX-74492 Resetting the bootcount fails with invalid environment block

debian/postinst
DLPX-74568 [Backport of DLPX-74079 to 6.0.8.0] Recovery environment postinst script swallows errors
DLPX-74519 [Backport of DLPX-74492 to 6.0.8.0] Resetting the bootcount fails with invalid environment block
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4848/
=> Error swallowing commit & Follow-on backport to 6.0/stage

debian/postinst
Used recovery-environment package from http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4875/ to test on IBM and OCI VMs.
=> DLPX-74575 IBM/OCI: Recovery environment becomes unreachable 

debian/postinst
ab-pre-push run: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4968/ (error appears to be environmental)
=> DLPX-75009 [Backport of DLPX-74575 tp 6.0.8.0] IBM/OCI: Recovery environment becomes unreachable

scripts/recovery_sync
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5802/
Manually tested on a VM with no .ssh directory, recovery sync still succeeded and the environment was still reachable (albeit with password instead of ssh keys).
=> DLPX-76730 delphix-bootcount.service failed due to a missing SSH file

scripts/recovery_sync
Clean backport of master commit
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5828/ (in progress)
=> DLPX-76845 [Backport of DLPX-76730 to 6.0.10.0] delphix-bootcount.service failed due to a missing SSH file

scripts/recovery_sync
The recovery_sync process copies the ssh keys from the main environment into the boot environment and converts them to a format that the `dropbear` ssh server understands, by using `dropbearconvert`. On Ubuntu 20.04 this process is failing with:
```
./usr/lib/dropbear/dropbearconvert openssh dropbear /etc/ssh/ssh_host_dsa_key etc/dropbear/dropbear_dsa_host_key
Error: Unrecognised key type
Error reading key from '/etc/ssh/ssh_host_dsa_key'
```
@pcd1193182 discovered that this was caused by all SSH keys now being generated with the proprietary OPENSSH header:
```
-----BEGIN OPENSSH PRIVATE KEY-----
```
instead of a header that is specific to the given key's type:
```
-----BEGIN RSA PRIVATE KEY-----
-----BEGIN EC PRIVATE KEY-----
```
By default `ssh-keygen` generates a key in the newer …
=> DLPX-76794 recovery_sync dropbear failure causes delphix-bootcount service to fail on Ubuntu 20.04

scripts/recovery_sync
=> DLPX-78310 [Backport of DLPX-76794 to 6.0.12.0] recovery_sync dropbear failure causes delphix-bootcount service to fail on Ubuntu 20.04

scripts/recovery_sync
This PR fixes the cleanup logic in the recovery_sync script to properly delete the temporary files in the case where the script fails.
http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/306/ in progress
=> DLPX-78981 rootfs out of space due to thousands of "recovery.img" files in "/boot"
